version: "1.0"
name: SampleStaticLibrary
sln_path: Project/windows/SampleStaticLibrary.sln
artifacts:
  include_headers:
    - Include/*
  link_libraries:
    - Dist/SampleStaticLibrary_${PLATFORM}_${CONFIGURATION}.lib
