version: "1.0"
name: SampleStaticLibraryE
sln_path: Project/windows/SampleStaticLibraryE.sln
artifacts:
  include_headers:
    - Include/*
  link_libraries:
    - Dist/SampleStaticLibraryE_${PLATFORM}_${CONFIGURATION}.lib
